# Generated by Django 3.1.7 on 2021-03-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=30)),
                ('birthday', models.DateField(default='2012-03-06')),
                ('gender', models.CharField(max_length=20)),
                ('owners_name', models.CharField(max_length=30)),
                ('owners_number', models.CharField(max_length=30)),
                ('medical_information', models.TextField()),
            ],
        ),
    ]
