# Generated by Django 3.1.7 on 2021-03-06 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homebuddy', '0002_auto_20210305_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='petname',
            new_name='pet_name',
        ),
    ]
